services:
  server:
    build:
      dockerfile: server/Dockerfile
    ports:
      - "1883:1883"

  client:
    build:
      dockerfile: client/Dockerfile

  broker:
    build:
      dockerfile: broker/Dockerfile
    ports:
      - "1883:1883"
